=== JACOB-Leonard/JACOB-Leonard.github.io/xml/cv.dtd
<!ELEMENT cv (personalInformation,experience,formation,skills,languages)>
<!ELEMENT personalInformation (titre,name,address,email)>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT experience (job+)>
<!ELEMENT job (title,company,year,description)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT company (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT formation (education+)>
<!ELEMENT education (degree,institution,year,projets?)>
<!ELEMENT degree (#PCDATA)>
<!ELEMENT institution (#PCDATA)>
<!ELEMENT projets (projet+)>
<!ELEMENT projet (#PCDATA)>
<!ELEMENT skills (skill+)>
<!ELEMENT skill (name,details)>
<!ELEMENT details (#PCDATA)>
<!ELEMENT languages (language+)>
<!ELEMENT language (name,level)>
<!ELEMENT level (#PCDATA)>

=== JACOB-Leonard/JACOB-Leonard.github.io/xml/cv_fr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cv SYSTEM "cv.dtd">
<cv>
    <personalInformation>
        <titre>Apprenti ingenieur informatique</titre>
        <name>
            Léonard JACOB
        </name>
        <address>
            Ile de france
        </address>
        <email>leonard.jacob@hotmail.com</email>
    </personalInformation>
    <experience>
        <job>
            <title>
                Développeur Full Stack
            </title>
            <company>
                Infotel Conseil
            </company>
            <year>2023</year>
            <description>
                Développement de sites web en Angular et d'applications Spring Boot.
            </description>
        </job>
        <job>
            <title>
                Développeur Web
            </title>
            <company>
                IPSL
            </company>
            <year>2022</year>
            <description>
                Développement de sites web et d'applications web.
            </description>
        </job>
    </experience>
    <formation>
        <education>
            <degree>
                Ingenieur Informatique
            </degree>
            <institution>
                Sup Galilée
            </institution>
            <year>2025</year>
            <projets>
                <projet>Projet Java</projet>
                <projet>Projet web semantique</projet>
                <projet>Projet OLOC</projet>
            </projets>
        </education>
        <education>
            <degree>
                DUT Informatique
            </degree>
            <institution>
                IUT de
            </institution>
            <year>2022</year>
        </education>
        <education>
            <degree>
                Baccalaureat Filière Scientifique
            </degree>
            <institution>
                Lycée
            </institution>
            <year>2020</year>
        </education>
    </formation>
    <skills>
        <skill>
            <name>
                Langages de programmation
            </name>
            <details>
                JavaScript, Python, Java
            </details>
        </skill>
        <skill>
            <name>
                frameworks
            </name>
            <details>
                React, Angular, Spring
            </details>
        </skill>
    </skills>
    <languages>
        <language>
            <name>
                français
            </name>
            <level>
                Langue maternelle
            </level>
        </language>
        <language>
            <name>
                Anglais
            </name>
            <level>
                Courant
            </level>
        </language>
    </languages>
</cv>

=== JACOB-Leonard/JACOB-Leonard.github.io/xml/cv_jp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cv SYSTEM "cv.dtd">
<cv>
    <personalInformation>
        <titre>ITエンジニア見習い</titre>
        <name>
            Léonard JACOB
        </name>
        <address>
            イル・ド・フランス        
        </address>
        <email>leonard.jacob@hotmail.com</email>
    </personalInformation>
    <experience>
        <job>
            <title>
                フルスタックデベロッパー            </title>
            <company>
                Infotel Conseil
            </company>
            <year>2023</year>
            <description>
                AngularウェブサイトとSpring Bootアプリケーションの開発。            
            </description>
        </job>
        <job>
            <title>
                ウェブデベロッパー            
            </title>
            <company>
                IPSL
            </company>
            <year>2022</year>
            <description>
                ウェブサイトやウェブアプリケーションの開発            
            </description>
        </job>
    </experience>
    <formation>
        <education>
            <degree>
                ITエンジニア            
            </degree>
            <institution>
                Sup Galilée
            </institution>
            <year>2025</year>
            <projets>
                <projet>Javaプロジェクト</projet>
                <projet>セマンティック・ウェブ・プロジェクト</projet>
            </projets>
        </education>
        <education>
            <degree>
                DUT Informatique
            </degree>
            <institution>
                IUT de Villetaneuse
            </institution>
            <year>2022</year>
        </education>
        <education>
            <degree>
                Baccalaureat Filière Scientifique
            </degree>
            <institution>
                Lycée Eugène Ionesco
            </institution>
            <year>2020</year>
        </education>
    </formation>
    <skills>
        <skill>
            <name>
                プログラミング言語            
            </name>
            <details>
                JavaScript, Python, Java
            </details>
        </skill>
        <skill>
            <name>
                フレームワーク
            </name>
            <details>
                React, Angular, Spring
            </details>
        </skill>
    </skills>
    <languages>
        <language>
            <name>
                フランス語
            </name>
            <level>
                母国語            
            </level>
        </language>
        <language>
            <name>
                英語
            </name>
            <level>
                流暢
            </level>
        </language>
    </languages>
</cv>

=== JACOB-Leonard/JACOB-Leonard.github.io/xml/cv_en.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cv SYSTEM "cv.dtd">
<cv>
    <personalInformation>
        <titre>IT engineer apprentice</titre>
        <name>
            Léonard JACOB
        </name>
        <address>
            Île-de-France
        </address>
        <email>leonard.jacob@hotmail.com</email>
    </personalInformation>
    <experience>
        <job>
            <title>
                Full Stack Developer
            </title>
            <company>
                Infotel Conseil
            </company>
            <year>2023</year>
            <description>
                Development of Angular websites and Spring Boot applications.            </description>
        </job>
        <job>
            <title>
                Web Developer
            </title>
            <company>
                IPSL
            </company>
            <year>2022</year>
            <description>
                Development of websites and web applications.            </description>
        </job>
    </experience>
    <formation>
        <education>
            <degree>
                Ingenieur Informatique
            </degree>
            <institution>
                IT Engineer            
            </institution>
            <year>2025</year>
            <projets>
                <projet>Java Project</projet>
                <projet>Semantic Web project</projet>
                <projet>Linear programming project</projet>
            </projets>
        </education>
        <education>
            <degree>
                DUT Informatique
            </degree>
            <institution>
                IUT of Villetaneuse
            </institution>
            <year>2022</year>
        </education>
        <education>
            <degree>
                Scientific Baccalaureate            </degree>
            <institution>
                Lycée Eugène Ionesco
            </institution>
            <year>2020</year>
        </education>
    </formation>
    <skills>
        <skill>
            <name>
                Programming languages            
            </name>
            <details>
                JavaScript, Python, Java
            </details>
        </skill>
        <skill>
            <name>
                Frameworks
            </name>
            <details>
                React, Angular, Spring
            </details>
        </skill>
    </skills>
    <languages>
        <language>
            <name>
                French
            </name>
            <level>
                Native language            
            </level>
        </language>
        <language>
            <name>
                English
            </name>
            <level>
                Fluent
            </level>
        </language>
    </languages>
</cv>
